version: '3'

services:
   api:
      build: ./web_api
      image: backend-a21
      ports:
         - "7203:7203"
         - "5203:5203"
      environment:
         - ASPNETCORE_HTTP_PORT=https://+:5203
         - ASPNETCORE_URLS=http://+:7203

   ng:
      build: ./web_ui
      image: frontend-a21
      ports:
         - "80:80"
      stdin_open: true
