version: '3'

services:
   api:
      build: ./web_api
      image: image12_rabbit
      ports:
         - "7203:7203"
         - "7204:7204"
      environment:
         - ASPNETCORE_HTTP_PORT=https://+:7204
         - ASPNETCORE_URLS=http://+:7203

   ng:
      build: ./web_ui
      image: image1_rabbit
      ports:
         - "80:80"
      stdin_open: true
